server:
  port: 8888

spring:
  application:
    name: config-server

  profiles:
    active: composite

  cloud:
    config:
      server:
        composite:

          # 1. LOCAL - highest priority
          - type: native
            search-locations: classpath:/config/

          # 2. GITHUB - lower priority
#          - type: git
#            uri: https://github.com/vashist01/config-server
##            branch location
#            default-label: config-server