datasource:
  url: jdbc:mysql://localhost:3306/account_db
  username: root
  password: root123
  driver-class-name: com.mysql.cj.jdbc.Driver

  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    leak-detection-threshold: 2000

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000

#############################################################
# RESILIENCE4J
#############################################################

resilience4j:

  ###########################################################
  # Circuit Breaker
  ###########################################################
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true

    instances:
      customer-service:

        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

        recordExceptions:
          - feign.FeignException
          - feign.RetryableException
          - java.lang.Exception

  ###########################################################
  # Retry
  ###########################################################
  retry:
    instances:
      customer-service:

        maxAttempts: 3

        waitDuration: 2s

        retryExceptions:
          - feign.FeignException
          - feign.RetryableException

        ignoreExceptions:
          - com.banking.account.exception.DuplicateAccountException

  ###########################################################
  # Bulkhead
  ###########################################################
  bulkhead:
    instances:
      customer-service:
        maxConcurrentCalls: 5
        maxWaitDuration: 2s

#############################################################
# ACTUATOR
#############################################################

management:

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

#############################################################
# LOGGING
#############################################################

logging:
  level:
    io.github.resilience4j: DEBUG
    org.springframework.cloud.openfeign: DEBUG