api:
  version: v1
  datasource:
    url: jdbc:mysql://mysql:3306/auth_db?createDatabaseIfNotExist=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update